[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_marketplace = "CexBmrzVQBJB9BKy2ujzVppkyL85jFVxxSWQ9BiWXspc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/eskaine/.config/solana/nft-marketplace-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
