[features]
seeds = false
skip-lint = false
[programs.devnet]
nft_marketplace = "EDZSvPjAq1NnENrc1vteT7CbegbCTgeR2t1Z9QyEGdKH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/eskaine/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
