[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_marketplace = "3emUs6bwmP7StdKakHe8pdbmLjhpZBsKuymy2sNHVxtL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/eskaine/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
